"""changes

Revision ID: 860cb4751269
Revises: c3b1c7128e47
Create Date: 2024-07-12 12:46:14.050076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '860cb4751269'
down_revision = 'c3b1c7128e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('shipping_address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('billing_address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('billing_address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('shipping_address',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
